apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 71-master-sshd-motd
  labels:
    machineconfiguration.openshift.io/role: motd
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - path: /etc/motd
        mode: 0644
        overwrite: true
        fileSystem: root
        contents:
          source: data:text/plain;charset=utf=8;base64,IyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIwojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjCgoKRGVwbG95ZWQgYnkgQXJnb0NEIHVzaW5nIE9wZW5zaGl0R2l0T3BzCgojIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjCiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMK
